### ISSUE TITLE
The jq command is required by 3D GAN / dltest

### ISSUE THREAD

**Issue by smatzek** [cern-it-efp/EOSC-Testsuite#5]
The `jq` command is required on the operating system running the test suite, and is required by the `getGpuPerNode` function [here](https://github.com/cern-it-efp/EOSC-Testsuite/blob/c4741cbed36cbe3be50d995f263dbd02b23fa591/src/kubernetesFunctions.py#L479
).

Failure to previously install this dependency leads to errors like this when running dltest:
```
From kubectl:
End of attempt 57: 0
/bin/sh: 1: jq: not found
```

The command was not installed by default in the minimal Ubuntu 18.04 and Ubuntu 20.04 images I used for the test suite driving node.

While installing this command is not difficult, it should possibly be listed under dependencies in the documentation if you do not use the docker container. This can help avoid the situation of users hitting the error and having to look through logs to know they must install it.

**Comment by ignpelloz** [comment]
Thanks for flagging this, Sam. The docs will be updated accordingly (next release 21.12).
